### ISSUE TITLE
Weed_Plant_Masks: why all images are dark

### ISSUE THREAD

**Issue by jingweimo** [lameski/rgbweeddetection#1]
Hello, 

Thanks for the shared dataset! I was wondering why the images in the folder of Weed_Plant_Masks are totally dark. There are no masks for plants and weeds.

Thanks!

**Comment by lameski** [comment]
They are labels valued 0, 1 and 2. Multiply by constant (i.e. 100) when visualizing.

**Comment by jingweimo** [comment]
Thanks!!
